INSERT INTO C##ESTATE.ELEC_MASTER (
    SECTOR, PLOT, CONSUMER_NO, LOCATION, ADDRESS_L1, ADDRESS_L2, ADDRESS_L3, METER_NO,
    METER_MAKE, METER_KW, NAME, CONSUMER_TYPE, PHASE, SUPPLY_PUR, TARIFF_CATG, CONSUMER_CATG,
    LOAD_SANC, MULT_FACTOR, ASSD_CONSPN, USER_PERNO, ENTRY_DT, METER_STATUS, CUM_UNITS,
    CUM_ADJ, OLDCUM_ADJ, STATUS, CUM_MON, REMARKS, METER_TYPE, SOLAR_METER_MAKE,
    SOLAR_METER_KW, SOLAR_LOAD_SANC, SOLAR_PHASE, SOLAR_MULT_FACTOR, SOLAR_METER_STATUS, SOLAR_METER_NO
) VALUES (
    'AB', '001', 'CON123456', 'Location 999', 'L1', 'L2', 'L3', 'M123456789',
    'MeterXYZ', 10, 'John Doe', NULL, 1, 'Domestic', 'LT1', 'CATG1',
    100, 2, 1000, 'USR123', SYSDATE, 'A', 10000,
    100, 0, 'A', 1, 'No remarks', 'MT',
    'SolarMake1', 5, 11, 1, 6,
    'A', 'SMTR12345'
);

INSERT INTO C##ESTATE.ELEC_MASTER (
    SECTOR, PLOT, CONSUMER_NO, LOCATION, ADDRESS_L1, ADDRESS_L2, ADDRESS_L3, METER_NO,
    METER_MAKE, METER_KW, NAME, CONSUMER_TYPE, PHASE, SUPPLY_PUR, TARIFF_CATG, CONSUMER_CATG,
    LOAD_SANC, MULT_FACTOR, ASSD_CONSPN, USER_PERNO, ENTRY_DT, METER_STATUS, CUM_UNITS,
    CUM_ADJ, OLDCUM_ADJ, STATUS, CUM_MON, REMARKS, METER_TYPE, SOLAR_METER_MAKE,
    SOLAR_METER_KW, SOLAR_LOAD_SANC, SOLAR_PHASE, SOLAR_MULT_FACTOR, SOLAR_METER_STATUS, SOLAR_METER_NO
) VALUES (
    'CD', '002', 'CON789012', 'Location 456', 'L1', 'L1', 'L3', 'M987654321',
    'MeterABC', 13, 'Jane Smith', NULL, 1, 'Domestic', 'LT1', 'CATG1',
    150, 3, 1000, 'USR123', SYSDATE, 'A', 20000,
    200, 0, 'A', 2, 'Other remarks', 'MT',
    'SolarMake2', 8, 15.5, 2, 3,
    'A', 'SMTR54321'
);

INSERT INTO C##ESTATE.ELEC_MASTER (
    SECTOR, PLOT, CONSUMER_NO, LOCATION, ADDRESS_L1, ADDRESS_L2, ADDRESS_L3, METER_NO,
    METER_MAKE, METER_KW, NAME, CONSUMER_TYPE, PHASE, SUPPLY_PUR, TARIFF_CATG, CONSUMER_CATG,
    LOAD_SANC, MULT_FACTOR, ASSD_CONSPN, USER_PERNO, ENTRY_DT, METER_STATUS, CUM_UNITS,
    CUM_ADJ, OLDCUM_ADJ, STATUS, CUM_MON, REMARKS, METER_TYPE, SOLAR_METER_MAKE,
    SOLAR_METER_KW, SOLAR_LOAD_SANC, SOLAR_PHASE, SOLAR_MULT_FACTOR, SOLAR_METER_STATUS, SOLAR_METER_NO
) VALUES (
    '01', '003', 'CON987654', 'Location 123', 'L1', 'L2', 'L3', 'M567890123',
    'Meter123', 8, 'Alice Johnson', 'Residential', 1, 'Domestic', 'LT1', 'CATG2',
    200, 4, 1500, 'USR456', SYSDATE, 'A', 15000,
    150, 0, 'A', 3, 'Sample remarks', 'MT',
    'SolarMake3', 7, 18.5, 1, 4,
    'A', 'SMTR67890'
);

INSERT INTO C##ESTATE.ELEC_MASTER (
    SECTOR, PLOT, CONSUMER_NO, LOCATION, ADDRESS_L1, ADDRESS_L2, ADDRESS_L3, METER_NO,
    METER_MAKE, METER_KW, NAME, CONSUMER_TYPE, PHASE, SUPPLY_PUR, TARIFF_CATG, CONSUMER_CATG,
    LOAD_SANC, MULT_FACTOR, ASSD_CONSPN, USER_PERNO, ENTRY_DT, METER_STATUS, CUM_UNITS,
    CUM_ADJ, OLDCUM_ADJ, STATUS, CUM_MON, REMARKS, METER_TYPE, SOLAR_METER_MAKE,
    SOLAR_METER_KW, SOLAR_LOAD_SANC, SOLAR_PHASE, SOLAR_MULT_FACTOR, SOLAR_METER_STATUS, SOLAR_METER_NO
) VALUES (
    'LN', '004', 'CON543210', 'Location 789', 'L1', 'L2', 'L3', 'M345678901',
    'Meter567', 12, 'Bob Williams', 'Commercial', 3, 'Industrial', 'HT1', 'CATG3',
    300, 5, 2000, 'USR789', SYSDATE, 'A', 20000,
    200, 0, 'A', 4, 'Other remarks', 'MT',
    'SolarMake4', 10, 22.0, 3, 5,
    'A', 'SMTR98765'
);
