INSERT INTO ELEC_MASTER (
    SECTOR, PLOT, CONSUMER_NO, LOCATION, ADDRESS_L1, ADDRESS_L2, ADDRESS_L3, METER_NO,
    METER_MAKE, METER_KW, NAME, CONSUMER_TYPE, PHASE, SUPPLY_PUR, TARIFF_CATG, CONSUMER_CATG,
    LOAD_SANC, MULT_FACTOR, ASSD_CONSPN, UPDATED_BY, UPDATED_DATE, STATUS, BILLING_DEMAND,
    TOTAL_AMT_PAID, NET_AMOUNT, RECOVERY_STATUS, NO_OF_MONTHS, REMARKS, MTR_REMARKS,
    SOLAR_METER_MAKE, SOLAR_METER_KW, SOLAR_LOAD_SANC, SOLAR_PHASE, SOLAR_MULT_FACTOR,
    SOLAR_STATUS, SOLAR_METER_NO
) VALUES (
    'AB', '001', 'CON123456', 'Location 999', 'L1', 'L2', 'L3', 'M123456789',
    'MeterXYZ', 10, 'John Doe', NULL, '1', NULL, 'A', 'Res',
    100, 2, NULL, 'USER01', TO_DATE('24/05/2024 12:25:54', 'DD/MM/YYYY HH24:MI:SS'), 'A', 1000,
    50.25, 40.75, 'A', 6, 'No remarks', 'T1',
    'SolarMtr1', 5, 11, '1', 6,
    'A', 'SM'
);

INSERT INTO ELEC_MASTER (
    SECTOR, PLOT, CONSUMER_NO, LOCATION, ADDRESS_L1, ADDRESS_L2, ADDRESS_L3, METER_NO,
    METER_MAKE, METER_KW, NAME, CONSUMER_TYPE, PHASE, SUPPLY_PUR, TARIFF_CATG, CONSUMER_CATG,
    LOAD_SANC, MULT_FACTOR, ASSD_CONSPN, UPDATED_BY, UPDATED_DATE, STATUS, BILLING_DEMAND,
    TOTAL_AMT_PAID, NET_AMOUNT, RECOVERY_STATUS, NO_OF_MONTHS, REMARKS, MTR_REMARKS,
    SOLAR_METER_MAKE, SOLAR_METER_KW, SOLAR_LOAD_SANC, SOLAR_PHASE, SOLAR_MULT_FACTOR,
    SOLAR_STATUS, SOLAR_METER_NO
) VALUES (
    'CD', '002', 'CON789012', 'Location 456', 'L1', 'L1', 'L3', 'M987654321',
    'MeterABC', 13, 'Jane Smith', NULL, '1', NULL, NULL, NULL,
    150, 3, NULL, 'USER02', TO_DATE('23/05/2024 12:25:54', 'DD/MM/YYYY HH24:MI:SS'), 'A', 2000,
    75.5, 60.25, 'A', 12, 'Other remarks', 'T2',
    'SolarMtr2', 8, 15.5, '2', 3,
    'A', 'SM'
);

INSERT INTO ELEC_MASTER (
    SECTOR, PLOT, CONSUMER_NO, LOCATION, ADDRESS_L1, ADDRESS_L2, ADDRESS_L3, METER_NO,
    METER_MAKE, METER_KW, NAME, CONSUMER_TYPE, PHASE, SUPPLY_PUR, TARIFF_CATG, CONSUMER_CATG,
    LOAD_SANC, MULT_FACTOR, ASSD_CONSPN, UPDATED_BY, UPDATED_DATE, STATUS, BILLING_DEMAND,
    TOTAL_AMT_PAID, NET_AMOUNT, RECOVERY_STATUS, NO_OF_MONTHS, REMARKS, MTR_REMARKS,
    SOLAR_METER_MAKE, SOLAR_METER_KW, SOLAR_LOAD_SANC, SOLAR_PHASE, SOLAR_MULT_FACTOR,
    SOLAR_STATUS, SOLAR_METER_NO
) VALUES (
    '01', '001', '12345677', 'Sector 01', '01', '02', '03', NULL,
    NULL, NULL, 'Johnn', 'Residential', '1', 'Domestic', 'LT1', 'CATG1',
    100, 100, 1000, 'USR123', TO_DATE('07/06/2023', 'DD/MM/YYYY'), 'A', 10000,
    100, 100, 'A', 100, 'Sample Remarks', 'MT',
    'SolarMake1', 3000, 8000, '1', 100,
    'A', 'SMTR12345'
);

INSERT INTO ELEC_MASTER (
    SECTOR, PLOT, CONSUMER_NO, LOCATION, ADDRESS_L1, ADDRESS_L2, ADDRESS_L3, METER_NO,
    METER_MAKE, METER_KW, NAME, CONSUMER_TYPE, PHASE, SUPPLY_PUR, TARIFF_CATG, CONSUMER_CATG,
    LOAD_SANC, MULT_FACTOR, ASSD_CONSPN, UPDATED_BY, UPDATED_DATE, STATUS, BILLING_DEMAND,
    TOTAL_AMT_PAID, NET_AMOUNT, RECOVERY_STATUS, NO_OF_MONTHS, REMARKS, MTR_REMARKS,
    SOLAR_METER_MAKE, SOLAR_METER_KW, SOLAR_LOAD_SANC, SOLAR_PHASE, SOLAR_MULT_FACTOR,
    SOLAR_STATUS, SOLAR_METER_NO
) VALUES (
    'LN', '001', '12345678', 'Sector 01', NULL, '02', '03', 'MTR12345',
    'Make12345', 5000, 'Heiseberg', 'Residential', '1', 'Domestic', 'LT1', 'CATG1',
    100, 100, 1000, 'USR123', TO_DATE('07/06/2023', 'DD/MM/YYYY'), 'A', 10000,
    100, 100, 'A', 100, 'Sample Remarks', 'MT',
    'SolarMake1', 3000, 8000, '1', 100,
    'A', 'SMTR12345'
);
